apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: cleanup
      image: ubuntu:20.04
      script: |
        #!/bin/bash
        echo "Cleaning up workspace..."
        rm -rf $(workspaces.shared-workspace.path)/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: install-dependencies
      image: python:3.10
      script: |
        #!/bin/bash
        pip install --upgrade pip
        pip install nose
        pip install -r $(workspaces.shared-workspace.path)/requirements.txt || true

    - name: run-tests
      image: python:3.10
      script: |
        #!/bin/bash
        echo "Running unit tests..."
        nosetests $(workspaces.shared-workspace.path)
